version: "3"

services:
  db-postgres-event:
    image: postgres
    ports:
      - "5435:5432"
    container_name: car_rent
    restart: always
    volumes:
      - ./banco-de-dados:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  banco-de-dados-evento:
